import React, { Fragment } from "react";

import classes from "./BodyDescription.module.css";

const BodyDescription = (props) => {
  const emails = [
    "Ethan reports on his mission trip in Chile. He has been working mostly over the phone and has visited some nearby church members and a town called Entre Lagos. He had an hour and a half conversation with a woman about baptism. He has taken some photos and included them in the email. He makes humorous comments about his friends, including Daniel, Francis, Aren, and Sebastian. He requests pictures of projects his friends are working on and jokes about sending a film he made. He asks for a sushi delivery if the FBI comes to his door. He mentions that Sebastian is welcome to visit, but he has to pay his own way if he doesn't have a good conversation. He requests fire photos from a study photoshoot with Goodwill Hunting equations. He thanks his friends for their messages and talks to them next week.",
    "Ethan is in rural southern Chile as a volunteer. Chilean national elections took place, the left-leaning candidate won, and there's some excitement in the air. Ethan is working with a new volunteer named Tanner, focusing on finding people and helping a local family get back to church. Ethan misses his friends and would love to hear updates from them. He is happy to hear Daniel is home and wishes he could join them for sushi. He provides encouragement to Sebastian and challenges him to make a beat in Db Locrian. Ethan's day off is now on Mondays.",
    "Ethan, who is doing missionary work in San Pablo, reports about his experience offering free manual labor and teaching English. He and Elder Robinson put up ads on Facebook marketplace to offer their services, but they only received a few responses for the wood cutting, but more for English classes. He mentions that chopping wood has been a stress reliever and adds that he won't be able to email Sega anymore, but he will spam Nintendo with requests to make Francis a DLC character. He also wishes Aren a happy birthday and asks about his plans for his birthday and the classes he and Francis are taking this semester. He ends the email by hoping that they are all doing well.",
    "Ethan, the writer of the email, and his colleague Tanner were unexpectedly sent to Lago Ranco, a different location than their usual assignment, to work with a new volunteer named Clyde. Despite the unexpected change of location, Ethan mentions that Lago Ranco is much prettier than San Pablo. He has been responsible for phone calls and Facebook communication for their work in Lago Ranco, San Pablo, and Entre Lagos. Ethan expresses gratitude for the birthday wishes he received and for the emails he receives from his friends, mentioning a specific story from Daniel and Francis, and wishes his friends well for the upcoming week.",
    "Ethan is currently experiencing some culture shock in Chile, including difficulty finding familiar foods and being surprised by the prevalence of stray dogs. He is also struggling with the frequent changes in his placement and the challenges of building genuine relationships in the current climate. Despite these challenges, Ethan is trying to stay positive and is grateful for the support of his friends.",
    "Ethan is in Valdivia, Chile and is enjoying his time there. He is working on a project with a local elder to update the records of the local church members and to encourage more people to attend church. He also mentions a funny incident with a wooden statue that turned out to be a carving of a penis.",
    "Ethan is having fun exploring moral philosophy and reminiscing about college days. He had a close encounter with aggressive dogs and had a humorous conversation with a drunk person about the Bible. He also shared pictures of an old railroad and puppies he found.",
    "Ethan and Elder Gunderson helped a man move dirt for his property and encountered his roosters. He asks about Daniel's AI and Aren's Italian cuisine knowledge and Sebastian's indie film-like life story. He also expresses his support for his friends and encourages Sebastian to write a heartbreak song.",
    "Ethan is excited about Sebastian's memes and wants to marry Sebastian's music teacher. He also mentions his feelings about the use of gas and critiques Kanye's STEM machine. He also talks about his week, which included unsuccessful video calls, getting stuck inside due to sickness, and finding a pastor's mixtape on the street.",
    "Ethan is currently in Chile and is renting an apartment, the couple that owns the apartment decided to extend the kitchen space and as a result, they had to cut off the water and gas for a week. He also mentions that he got rejected by a girl wearing a Demon Slayer jacket and he is also trying to help church members come back to church. He also mentions he is going to watch Batman and is looking forward to a food and sights day in SD.",
    "Ethan apologizes for not being able to send an email due to a technical issue. He will be sending a double edition next week. He expresses gratitude towards his friends and mentions that he misses everyone.",
    "Ethan had an interesting week, as he and his companion Elder Gunderson decided to try door knocking in Southern South America, where they met a couple who were both deaf and mute. They were able to communicate through gesturing and writing notes, and the couple expressed interest in hearing a message. They also got a new roommate in the form of a local cat who has attachment issues and they named her Cardi C. Ethan also mentioned that they have been working with several people and teaching English, and also had a fun time playing soccer with other missionaries despite the rain.",
    "Ethan is currently on a mission in Chile and this week he had to drop off his companion at the bus station and meet up with two other elders. He did not get to stay with his desired companion and instead was paired with Elder Viloria. He is feeling settled in Chile and is taking advantage of the opportunity to help people there, but he is also missing home. He also talks about his current physical training routine, new music and his friend's coming out.",
    "Ethan, who is a missionary for the Church of Jesus Christ of Latter Day Saints, had some interesting experiences this week. He encountered a group of people wearing white robes and holding candles and wooden crosses and later met a man who asked about their meetings and wanted to attend. He also set up a visit with a woman from Haiti, who unexpectedly came to their church and he is looking forward to working with her.",
    "This email is from Ethan, who is wishing Daniel a belated happy birthday, and discussing the fast passage of time. Ethan also mentions Sebastian's upcoming physics final and shares his own experience with getting pulled over. He also talks about the weather, learning to make arepas with Elder Viloria, and thanks the group for writing and sending pictures.",
    "Ethan is catching up with friends, mentioning their recent activities and reminiscing about past experiences together. He also mentions his own busy week as a missionary, including teaching and visiting with new families, and having a church activity with good food. He also mentions his plan to make arepas for his friends when he returns.",
    "Ethan, who is a missionary in Valdivia, Chile, had a slow week but met a character from Colorado with a perfect American accent dressed in a black jacket and beanie. The guy had a 'CHAD energy' and shared a hilarious story about his marriage to a Chilean woman. Ethan also mentions his recent stomach issues, which he learned were caused by a bacteria he contracted from dogs, leading to a personal vendetta against the Valdivian dog population. He also shares some updates with his friends Sebastian, Daniel and Aren, and asks about Francis.",
    "Ethan has finished reading emails from his friends, Sebastian, Daniel, and others. He suggests Sebastian open a bakery and outsource linear algebra homework to Daniel in exchange for muffins. He is excited about Sebastian's baking skills and wants to eat anything baked by him. He also mentions he is going to work as a missionary in Punta Arenas and that is going to be freezing. He also shares a story he heard from a Chilean church member about Chilean history.",
    "Ethan is safe in Punta Arenas, Chile and is working with a new Elder named Elder Soelberg. They are trying to help a couple come to church and helping one member of their church overcome a drinking problem. He also mentions that the penguins had left due to the cold weather and he wishes he could have been there for some of the events that his friends were having back home.",
    "Ethan is a missionary working in Chile and he is surprised to learn that Betty White has died. He and his colleague Elder Soulberg are planning to visit a shopping center called Zona Franca, which does not charge taxes, and he is looking forward to buying some new headphones and a parka. He also talks about the challenges they are facing while working in the area, and shares some updates on his friends and family.",
    "Ethan writes an email to his friends, discussing various topics, including Francis's upcoming trip to Italy, Daniel's laughter and hangout, Sebastian's love for Trader Joe's and a new experimental album he recommends, and Ethan's own work on evangelism. Ethan also mentions Aren's interest in marine biology and encourages him to try Workaway for travel, and the group's plan to make a curated list of recommendations for music, movies, and other things. He also mentions a woman they met who was working on her patio and who they shared a scripture and a prayer with, and that they made posters with their number and a message to post on poles.",
    "Ethan apologized for not being able to write an email this week due to some hiccups and that Mondays are the only days he can write. He welcomes Aryaan to the group and plans to explain more next week about his current location in Punta Arenas. He also included pictures from Punta Arenas and mentioned that it snowed earlier in the week and he is having trouble processing that it's June.",
    "Ethan and his partner Elder Soelberg have been finding some people interested in listening to their message and he is consistently visiting a woman named Paulina. He also mentions that he has been walking by a Jehovah's Witnesses stand and finds the experience trippy. He also gives updates on his friends' activities, including Sebastian's chef skills, Francis' transfer applications, Daniel's gym habits, and Aryaan's switch to software engineering. He expresses appreciation for his friends and plans to ride Tatsu at Six Flags once he returns. He also mention that he found some original music on Jehovah's Witnesses website.",
    "Ethan describes an interesting experience from the previous day where he and a companion went to a house they had been wanting to visit and asked to share a message with the family. However, the conversation turned into a 45-minute sermon and a prayer circle that Ethan found himself participating in. He also mentioned that he has been converted to drinking mate. He expresses appreciation for the emails and asks for someone to take care of a person named Hue.",
    "Ethan writes to his friends about his recent experiences, including eating a strange dish called curanto, participating in a baptism for a man named Filiberto, and adjusting to the limited daylight and icy conditions in Punta Arenas. He mentions his friends' recent activities, such as Sebastian's sister's opportunity in bioinformatics, Daniel and Francis' night at the movies, and Aren's job as a lifeguard. He expresses appreciation for their support and updates, and sends greetings to their families.",
    "Ethan writes about his experiences in an English class where he realized he's starting to think in Spanish and how his English is taking on more Spanish syntax. He also mentions enjoying an indie rap artist named Montell Fish and how his music is uplifting and self-affirming. He also mentions the winter weather and success with sharing their faith with people in their neighborhood and getting to know one woman named Pamela. He also mentions a yearly tradition in the Punta Arenas area where people gather on the beach in the middle of winter to charge into the ocean and dance in freezing temperatures. He also gives updates to Sebastian, Daniel, and others in the group and expresses his love for them.",
    "Ethan writes to his friends about his experiences in Punta Arenas, Chile. He describes a windstorm that hit the area and how their apartment shook as a result. He also describes a trip to a semi-nearby neighborhood that he hadn't been to before and how the streets dogs were 'completely insane.' He also mentions a visit with someone named Pamela and how it was disrupted by construction work. He also talks about how inflation is depleting chicken resources and how the recent election made his milk go bad. He also mentions that he will be making his own PC and will be enlisting the help of a friend named Daniel. He also mentions that he has started baking and is looking for tips to improve his baking. He also mentions that he is looking forward to his friends' presentation and that he is glad they feel comfortable with it. He ends the email by expressing how much he loves and misses them and asking them to send a hello to their families for him. He also mentions that he found a 'drippiest car' and that it made him think of a friend named Francis.",
    "Ethan shares about his recent experiences door knocking, including a visit with a couple who had been struggling with the husband's 'sixth sense' and a meeting with a man who had a lot of questions about Old Testament prophecies and Islam. He also mentions a chance encounter with a couple from Idaho and mentions the phone troubles of a friend and another friend's internship opportunities. Overall, Ethan is thinking of his friends and hoping they are doing well.",
    "Ethan mentions a difficult experience where they helped a woman who had been haunted by a bitter spirit for months. They listened to her, shared some comforting scriptures, and cast out the spirits in the name of Christ. The woman felt much better afterwards and they will continue to help her this week. He also mentions a happy experience where they visited a family whose door he felt impressed to knock on a month ago and they were fun and kind. Ethan also mentions that Chile is politically active and they are voting on whether or not they want to rework the entire Chilean constitution. He also mentions a conversation he had with Sebastian about Julia's pipeline theory and how he is interested in hearing it in full. He also mentions a conversation he had about mediums and how he doesn't have a clear stance on it. Finally, he mentions that he is looking forward to getting wheels and pimping out his car. He also mentions that he is enjoying Minecraft as a way to unwind and that he finds Aren's lifeguard methods chaotic and entertaining.",
    "Ethan writes about his experiences as a missionary in Punta Arenas. He mentions his excitement about a shirt that one of his friends, AREN, is wearing and mentions that he is jealous that AREN got to go to Six Flags and ride the Wonder Woman ride. He also talks about Sebastian's cooking and photography, and thanks him for recommending a book to him. He also mentions that he is looking forward to catching up with Daniel and taking a motorcycle joyride with him. He also mentions that he is available to answer any questions about the Bible and talks about a specific instance where he and another missionary helped a friend in need by giving him a mattress. He also talks about working with a woman named Paula and her two young daughters, who are both sweet but also quirky. He also talks about visiting rural areas of Punta Arenas and spending time with a man named Marcos who is building a cabin and learned how to do it from watching videos on YouTube. He also expresses his love and gratitude to his friends for writing to him.",
    "Ethan attempted to make tortilla de papa but had difficulty getting the dough to hold shape. He tried again the next day and was successful. He also made homemade corn dogs that turned out well. He also saw a street horse in his neighborhood, and mentions updates from his friends and wishes them well.",
    "Ethan discusses the TV show Bojack Horseman, a corn dog recipe, and the difficulty of finding interested participants for his work with a family from Columbia. He also mentions his lack of motivation after a setback in his work and shares his success in making cheese-filled tortillas de papa. Additionally, he expresses disappointment over one friend's recent purchase of an iPhone.",
    "Ethan expresses excitement in the email about the dorms and apartment space of his friends who are in college. He makes reference to the TV show Bojack Horseman. He also discusses how his mission trip in Chile is going, including meeting new families, attending his English class and a visit from the mission president. Ethan also shares anecdotes about running to make a dinner reservation and finding a funny shaped dog.",
    "Ethan mentions knocking on doors and speaking with people about their spiritual beliefs, as well as helping a member of a nearby congregation move and participating in an English class. Ethan and his group were also required to stay inside on a specific day due to potential public conflicts. At the end of the email, Ethan mentioned that he went go-karting on his day off and had a good time, and also greets a friend named Francis who recently met some family from the UK.",
    "Ethan had a good week in Punta Arenas, Chile. He made two new friends, Rosita and Fernanda, and gave a blessing of health and strength to Francisca's baby daughter. Friday was a church activity celebrating 18 de Septiembre and it was a lot of fun. Fernanda came to the activity and took a chapel tour and she was emotional at the end and she said she would love to be a part of the community. On Saturday, he ate too many empanadas. On Sunday, he was hit by a cold and was very tired. He's almost halfway done with his mission and can't wait to see his family and friends again. Happy birthday to Aryaan, who just turned 20.",
    "Ethan's email describes a few recent events in his life, including a surreal experience where he and a friend helped an older woman cross the street and ended up visiting her at her house for a Bible study, which turned into a conversation about the sabbath day. He also mentions meeting a new person named Cesar who was open to discussing the restoration of the ancient church of Christ and attended church. Additionally, Ethan notes that there is a construction machine company in Chile that is making clothes with Dragon Ball Z designs, and that there are job advertisements for gigs in Antarctica with a good payout. Lastly, Ethan expresses his love for his friends and family and mentions that it is always a highlight of his week to hear from them.",
    "Ethan's email updates his friends on his recent experiences, including an unexpected greeting from a child, playing volleyball at a church event, and encountering horses frequently. He mentions that two visits he had over the weekend went well, with one friend expressing gratitude for their spiritual impact on him but choosing to continue in the Catholic church. Ethan also responds to Daniel's suggestion of welding or working in construction in Antarctica and Sebastian's book and movie recommendations. He also mentions his plans to focus on working out and bulking up with Elder Soelberg, and expresses excitement to talk to his friends again next week.",
    "Ethan's email reflects on the concept of identity, discussing how it can change over time and how one can stay true to it. He also mentions his recent spiritual reflection on taking the sacrament and the commitment to carry Christ's name. He shares some updates on his personal life, including the weather, visiting people, and a volleyball challenge with Daniel. He also mentions his friends Sebastian, Daniel, Aren, Francis, and Aryaan and expresses that he misses them.",
    "Ethan is currently serving as a missionary in Chile and reports that the mission president has asked them to focus on helping members of the church return. They have been going door-to-door to addresses in the area and trying to track down people who are not currently active in the church. He is also working on a pilot program to create a more accurate map of their sector using Google Maps. Ethan also shares that he had an interesting cultural experience at a corner store and enjoyed playing with a 6-week-old kitten. He also mentions that he is looking forward to returning home and catching up with friends.",
    "Ethan had a great week as he met two new friends, Sandra and Jorge, and had great visits with them. He and his friends also invited them to church, and they both came. Ethan is also heading to Puerto Montt for a meeting with his mission and he shared some funny episodes that he experienced. He also wished his friends Daniel, Sebastian, and Aryaan luck and well-being and expressed that he missed them all.",
    "Ethan, a missionary in Chile, recounts his recent trip to Puerto Montt. He and his group encountered issues with their tickets and were not able to board their flight, but they were able to catch a flight to Santiago and make it to their destination that evening. He mentions his experience in Santiago, including seeing a McDonald's and a Starbucks, and having a good time with other missionaries. He also mentions his friends back home, including Aren and Francis, and mentions a card game called skull king that he enjoyed playing. He also mentions a dog they found at the Puerto Montt airport and named Santiago, and wishes his friends well with their studies and personal lives.",
    "Ethan is now in Futrono, a small town on the side of a lake in the north of Chile. He is working with a missionary Elder Kent, and they are trying to focus on helping members of the Church and less active members of the Church in the area. Ethan describes the area as beautiful and green, with a warm climate and strong 'Woah, I'm in South America' feelings. He also mentions that he misses his friends and hopes they are safe.",
    "Ethan's email updates his friends on his experiences as a missionary in Futrono, Chile. He describes the small town atmosphere and the help and support he receives from other members of the branch. He also shares about visiting a woman named Eva and plans to organize another visit with her and her husband with the help of church members from Haiti to assist with language barriers. He also mentions about his other experiences such as going on a lunch with a member who lives far outside the city and having to trek through a field dotted with cows, and how it's been raining a lot and waiting for the summer weather to come through in December. He also shares that he and his companion had to cut the bread with an axe because it was too dry to eat. He also asks his friends about their goals and how they're doing in their academic and personal life, and expresses his excitement for Daniel's internship and wishes them all the best. He also mentions that he has changed a lot since being a missionary and that he's grown a lot spiritually and has come to trust God a lot more in his life personally.",
    "Ethan describes his week as a missionary, including going on a trip with other missionaries to a tourist town, talking to people on the street, and participating in a 'tortilla fight' with another missionary. On Thursday, Ethan went to the city of Osorno for a doctor's appointment for his knee. During this trip, he went to a music store and a clinic, encountering a variety of people and sounds along the way. Ethan also mentions that he is worried about a new missionary, Elder Patterson, who is having a difficult time adjusting to his role and reminds Ethan of himself when he first started as a missionary.",
    "Ethan's email updates his friends on his recent ankle scan, which turned out to be an MRI, and the results of which he will know next week. He also mentions that he and his companion, Elder Warren, both caught colds and had to take naps to recover. He also shares some stories about the quirks of daily life in his mission, such as finding a slug on his comb and a clogged drain in his bathroom. He expresses excitement about upcoming events like Halloween and a friend's Friendsgiving. He also jokingly asks about a vote his friends had in which one of them voted him as most likely to have sexual relations with Penny.",
    "Ethan recently shared his experiences from the past week. He mentioned that he has only just started to realize that it is December, as the weather in his location does not match the season. He also shared an interesting encounter with a local crackhead in his town of Futrono, who is known for his tall and lanky appearance and tendency to randomly curse and swear. Additionally, Ethan received results from a scan on his ankle and was diagnosed with light tenosinovitis, he plans to see a doctor to discuss treatment options. He also mentioned his participation in a stake conference in Valdivia and reconnecting with a family he had helped while serving as a missionary. Ethan also shared his current interest in Halloween and playing chess with his companion Elder Warren. He also mentioned his excitement to receive an email from his friend Francis, and acknowledged updates from his other friends about their recent activities.",
    "Ethan apologizes for not having enough time to write in detail, but plans to catch his recipients up on his recent events in a two-episode special email the following week. He mentions that he was called in to replace someone in the mission office, which handles administrative tasks other than leadership roles. He also mentions that a number of people are finishing their missions and new missionaries are arriving, causing a rush of activity. Ethan is currently working as the Historian, which he describes as an adventure, and mentions that he is being trained by another missionary, Elder Viloria, who is moving to a different part of the mission soon. He expresses hope that his recipients and their families are safe and doing well, and mentions that he had a good time at Arrowhead Aren.",
    "Ethan, who is working with Elder Costa in Puerto Montt, Chile, had two memorable moments during the past week. On Tuesday, they visited a woman named Adriana who was struggling emotionally and physically from caring for her husband with Alzheimer's. They provided comfort and gave her a blessing, and plan to help her further in January. On Christmas Eve and Christmas Day, a couple in the church invited missionaries over for dinner and lunch, and one of the highlights was seeing the outhouse decorated like the Shrek outhouse. Ethan is glad to hear that his family had a good holiday and is looking forward to the new year.",
    "Ethan and his fellow missionaries had an eventful week, including accidentally lassoing an endangered bird and needing to rescue it. They also purchased a new laminator and went to a nearby national park. They also spent time doing office work and talking to people in the community, and even went door-to-door with a church member. They also had a fun night learning Latin dances from Elder Costa. Overall, Ethan is looking forward to coming back home in November and to the Lechner family conversations.",
    "Ethan had a successful week in Chile, including getting a work visa, attending a leadership meeting, and having a positive conversation with a family about how God can help families. He also had a fun and unexpected experience at a baseball game behind a prison, and is looking forward to meeting up with the family again this Saturday. He also expresses well wishes to his friends, including Sebastian for writing a play, and expresses excitement for future plans like watching a movie together and seeing art. He also mentions that his mother sent him a Donkey Kong figurine for Christmas and it is now one of his favorite desk trinkets.",
    "Ethan is a missionary in Puerto Montt, Chile who has recently been doing errands and shopping at the mall. He had an adventure this week where he received a text from the Mission President that the Elders in Gamboa were receiving death threats, so he sent them new SIM cards and the President is removing them from the area for safety reasons. He also made cheese with one of the Elders using milk and vinegar. He apologizes for the short email and recommends a R&B album by Lianne La Havas to one of the recipients. He also plans to listen to some songs by SZA.",
    "It sounds like Ethan has had a very busy and exciting week, filled with meeting new people and experiencing new things. It's great that Ethan was able to connect with Jesus and Raulis and have meaningful conversations with them. It's also wonderful that Ethan was able to help Elder Ramirez adjust to his new surroundings and that he's been a great help in the office. It's interesting to hear about Ethan's encounter with Noah, the guy from Arizona who's currently on a six-month backpacking trip around South America. It's inspiring to hear that he followed through with his dream and it sounds like it's given Ethan some inspiration to consider doing something similar in the future. Thanks for sharing all the exciting updates, it's great to hear from Ethan!"
  ];
  return (
    <Fragment>
      <div className={classes.description}>{emails[props.date]}</div>
    </Fragment>
  );
};

export default BodyDescription;
